### ISSUE TITLE
Improve to process lots of roms

### ISSUE THREAD

**Issue by rollecode** [grayaii/rom_cleaner#2]
Hello! I love your tool. However in a ROM folder that has over 5000 roms the script crashes:

```
rolle@retropc:~/RetroPie/roms/c64$ clean_roms --rom_dir .
using cached list from: roms.txt
Traceback (most recent call last):
  File "/usr/local/bin/clean_roms", line 159, in <module>
    all_roms.add_rom(Rom(full_path_filename))
  File "/usr/local/bin/clean_roms", line 63, in __init__
    self.base_filename = self.describe_rom(full_path_filename)
  File "/usr/local/bin/clean_roms", line 84, in describe_rom
    ret_tokens.append(ret_base_filename[s_p[i]:e_p[i] + 1])
IndexError: list index out of range
```

Can you update the script so that it handles larger amount of roms?

**Comment by artifexor** [comment]
i think this error is related to an unbalanced square brackets or parentheses in filename, for example in filename
```ZZZ-UNK-NEEDS LOADER-WACKY WAITERS - SYS 7296 (Y)(-)[b [B][B].zip```
there is more opening square brackets than closing and therefore the closing indexes are out of range (3 opening vs 2 closing). in your example because the error is happening with _p variable is most likely related to an unbalanced parentheses.

**Comment by jhartshorn** [comment]
I'm rubbish at programming, but for anyone else experiencing this issue here's a quick hack that helped me: add the line below just above the line that throws the error so you can identify the filename causing the problem.

`print(ret_base_filename)`

**Comment by gpapp** [comment]
To balance the brackets, this crude code may help. It will not work with more than one open brackets/parantheses, but fixes those cases, where the filename is truncated.

```
...
        e_b = self.find(ret_base_filename, ']')

        d_p = ret_base_filename.rfind('.')
        if (len(s_p)>len(e_p)):
            e_p.append(d_p)
        if (len(s_b)>len(e_b)):
            e_b.append(d_p)

        for i in range(len(s_p)):
...
```
